- name: frontend setup
  hosts: all
  become: yes
  tasks:
    - name: install Nginx
      ansible.builtin.dnf:
        name: nginx
        state:

    - name: copy expense nginx configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf



    - name: clean up the old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent


    - name: create app directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory


    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes


    - name: Start Nginx
      ansible.builtin.systemd_service:
       state: restarted
       name: nginx


  # frontend setup
  # frontend setup

