- name: Disable default nodejs version module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs module for V20
  ansible.builtin.shell: dnf module disable nodejs -y

- name: install NodeJS
  ansible.builtin.dnf:
    name: NodeJS
    state: installed

- name: Adding application user
  ansible.builtin.user:
    name: expense

- name: Import app pre requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req


- name: Download nodejs Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: copy backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: install python mySQL Client
  ansible.builtin.pip:
    name:
      Pymysql
      cryptography
    executable: pip3.9






- name: Load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: expenseApp@1
    login_host: mysql-dev.sairajd.online

- name: start backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes
    daemon_reload: yes


