
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: start mysql service
    ansible.builtin.systemd_service:
      name: mysql
      state: started
      enabled: yes

  - name: install python MySQL Client
    ansible.builtin.pip:
      name:
        - pymysql
        - cryptography
      executable: pip3.9

  - name: check the DB connection with our password
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql-dev.sairajd.online
      filter: version
    register: mysql_connection_output
    ignore_errors: yes


  - name: setup MySQL password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
    when: mysql_connection_output.failed is true

